### Работа с данными (чтение, запись).

Для чтения и записи файлов в python используется встроенная функция **open**. 

Рассмотрим пример записи и чтения файла с использованием **open**

Открытия файла для записи (содержимое файла при этом уничтожается):

Пример 1:

In [ ]:
test = "Некоторый текст"
fw = open("test_1.txt", 'w')
fw.write(test + "\n")
fw.close()

Открытия файла для чтения:

Пример 2:

In [ ]:
fr = open("test_1.txt")
test = fr.read()
fr.close()
print(test)

Некоторый текст



Убедитесь, что повторная запись в файл в примере 1 уничтожает его содержимое.

Открытие файла для до записи (содержимое файла сохраняется):

Пример 3:

In [ ]:
test = "Некоторый другой текст"
fa = open("test_1.txt", 'a')
fa.write(test + "\n")
fa.close()

Убедимся, что файл не был очищен 

In [ ]:
fr = open("test_1.txt")
test = fr.read()
fr.close()
print(test)

Некоторый текст
Некоторый другой текст



### Рассмотрим функцию **open**: 


**open**( <br>
    file, <br>
    mode='r', <br>
    buffering=-1, <br>
    encoding=None, <br>
    errors=None, <br>
    newline=None, <br>
    closefd=True, <br>
     opener=None, <br>
)<br><br>
Описание основных аргументов (в рамках курса): <br><br>
**file** - путь и название файла.<br>
**mode** - (основные) 'r' открыть для чтения (по умолчанию), 'w' - открыть для записи очищая файл, 'a' - открыть файл для дозаписи в конец файла, 'b' - режим чтения/записи байтов. <br>
**encoding** - имя кодировки, используется  только в текстовом режиме. Выбор по умолчанию зависит от платформы. Пример 'utf-8' <br>
Для дополнительной информации используйте **"?open"**


### Методы записи в файл 
.writable() - возвращает True/False в зависимости от возможности записи в файл. <br>
.write(text) - записывает текст в файл. Возвращает длину записанного текста.  <br>
.writelines(lines) - записывает список текстовых строк в файл.  <br>
  

### Методы чтения из файла 
.readable() - возвращает True/False в зависимости от возможности чтения файла. <br>
.read(size=-1) - Чтение заданного количества символов **size** или пока не достигнет конца файла.  <br>
.readline() - Чтение одной строки из файла. Возвращает считанную строку. Возвращает пустую строку в случае конца файла.  <br>
.readlines() - Чтение всех строк из файла. Возвращает список считанных строк. <br>

### При работе с файлами с использованием функции **open**, надежнее использовать конструкцию **with**. Использование **with** позволяется быть уверенным, что в случае ошибки доступа к файлу (после открытия) файл будет закрыт. 

Пример 4:

In [ ]:
text = "используем with"
with open("test.txt",'w',encoding = 'utf-8') as f:
    f.write(text + "\n")

In [ ]:
with open("test.txt",'r',encoding = 'utf-8') as f:
    text = f.readlines()
print(text)

['используем with\n']


### Модуль **pickle** для записи и чтения объектов python

Данный модуль позволяет сохранить объект python вместе с состоянием по некоторому выбранному протоколу. Модуль также позволяет загружать объекты в программу. Объекты можно перенести на другое устройство (кроссплатформенность).  

Подключение модуля:

In [ ]:
import pickle

сохранение объекта осуществляется через функцию **.dump**

**pickle.dump**( <br>
    obj, <br>
    file, <br>
    protocol=None, <br>
     \*, <br>
    fix_imports=True, <br>
    buffer_callback=None, <br>
)<br><br>
Описание основных аргументов в рамках курса: <br><br>
**obj** - объект для записи.<br>
**file** - файл открытый в побайтовом режиме записи. <br>
**protocol** - выбор протокола записи данных. доступные значения 0, 1, 2, 3, 4, 5. По умолчанию 4 <br>
Для дополнительной информации используйте **"?pickle.dump"**


чтение объекта осуществляется через функцию **.load**

**pickle.load**( <br>
    file, <br>
     \*, <br>
    encoding='ASCII',<br>
    errors='strict',<br>
    buffers=(),<br>
)<br><br>
Описание основных аргументов в рамках курса: <br>
**file** - файл открытый в побайтовом режиме чтения. <br><br>

При чтении данных **protocol** определяется автоматически <br>
Для дополнительной информации используйте **"?pickle.load"**


### Пример использования **pickle**

создадим матрицу **А** 

In [ ]:
import numpy as np

In [ ]:
A = np.random.random((3,3))
print(A)

[[0.14237529 0.81898281 0.79626286]
 [0.53532949 0.20329638 0.35353183]
 [0.35973966 0.64636655 0.39909561]]


Сохраним матрицу A в файл

In [ ]:
with open("matrix_A.pck","wb") as f:
    pickle.dump(A,f)

Считаем матрицу из файла

In [ ]:
with open("matrix_A.pck","rb") as f:
    B=pickle.load(f)

In [ ]:
print(B)

[[0.14237529 0.81898281 0.79626286]
 [0.53532949 0.20329638 0.35353183]
 [0.35973966 0.64636655 0.39909561]]


### Чтение и запись данных NumPy

In [2]:
import numpy as np

#### Запись данных и последующее чтение в бинарном виде

библиотека NumPy имеет две функции: **save()** и **load()**, которые позволяют сохранять получать данные, сохраненные в бинарном формате.

In [3]:
data = np.random.random((3,4))
data

array([[0.77421907, 0.31570661, 0.4576681 , 0.44970191],
       [0.51890013, 0.78412145, 0.82411817, 0.83900723],
       [0.03786652, 0.23014039, 0.62757818, 0.19871318]])

In [4]:
np.save("np_save_data",data)

**np.save**( <br>
    file, <br>
    arr, <br>
)<br>
Описание основных аргументов: <br><br>
**file** - путь и название файла. **Расширение файла .npy добавляется автоматически**.<br>
**arr** - массив для записи. <br>

Чтение данных по средствам функции np.load(). Она требует определить имя файла в качестве аргумента с расширением .npy!

In [5]:
ldata = np.load('np_save_data.npy')
ldata

array([[0.77421907, 0.31570661, 0.4576681 , 0.44970191],
       [0.51890013, 0.78412145, 0.82411817, 0.83900723],
       [0.03786652, 0.23014039, 0.62757818, 0.19871318]])

### Чтение табличных данных средствами NumPy

создадим таблицу. Обратите внимание, что некоторые элементы пропущены.

In [ ]:
table = [['i','x','y','p'],[1,0,0,1],[2,'',1,1.5],[3,1,0,''],[4,1,1,2.5]]
table

[['i', 'x', 'y', 'p'],
 [1, 0, 0, 1],
 [2, '', 1, 1.5],
 [3, 1, 0, ''],
 [4, 1, 1, 2.5]]

сохраним таблицу в файл

In [ ]:
with open("table.csv",'w') as f:
    for line in table:
        k=0
        for a in line:
            if k>0:
                f.write(",")
            k=1
            f.write(str(a))
            
        f.write("\n")

Для чтения табличных данных NumPy имеет функцию **np.genfromtxt**

In [ ]:
tdata = np.genfromtxt('table.csv', delimiter=',', names=True)

In [ ]:
tdata

array([(1.,  0., 0., 1. ), (2., nan, 1., 1.5), (3.,  1., 0., nan),
       (4.,  1., 1., 2.5)],
      dtype=[('i', '<f8'), ('x', '<f8'), ('y', '<f8'), ('p', '<f8')])

Первый аргумент соответствует пути и имени файла, аргумент **delimiter** - используемый разделитель, аргумент **names** указывает на наличие заголовка в таблице. Обратите внимание, что пропущенные элементы в таблице заполнились **nan**.